### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by 1shevelov** [heroiclabs/fishgame-godot#1]
Hello,
I found this on [the forum](https://forum.heroiclabs.com/t/fish-game-an-open-reference-game-using-nakama-for-multiplayer/)

Could you, please, elaborate on the game
1) What stage of development is it on? Is it playable?
2) Could you provide some plans on development? May be just a short list of features that are planned next.

I understood that the primary purpose of the game is to demonstrate the use of Nakama. What Nakama features are already implemented? Which ones are you planning to implement? Please, add some details as where in the code they are invoked, may be some other details that could be of help for Nakama newbies.

Thank you, that will definitely be of use for many Godot users.

**Comment by erlend-sh** [comment]
The game is at a playable stage.

Main Nakama features are:
- User accounts
- Matchmaking
- Leaderboards
- Real-time connection

David is now working on a tutorial that’ll walk through all of this.

**Comment by mofirouz** [comment]
@dsnopek if you could kindly add info on what features of Nakama are being used in the game, as well as how to play the game (which keys - see #2) that would be super helpful. Thanks!

**Comment by dsnopek** [comment]
@mofirouz Absolutely!

The README.md has been updated with the controls and list of Nakama features used.
